# .nosana-ci.yml
global:
  image: alpine
  trigger:
    push:
      branches:
        - "*"

jobs:
  - name: build
    commands:
      - echo "building..."
      - mkdir my-build
    artifacts:
      - name: my-build

  - name: test
    commands:
      - echo "testing..."
    resources:
      - name: my-build

  - name: deploy
    commands:
      - echo "deploying..."
    resources:
      - name: my-build