# .nosana-ci.yml
global:
  image: nosana/solana
  trigger:
    push:
      branches:
        - "*"

jobs:
  - name: build
    commands:
        - npm ci
        - npm run build:program-rust
    artifacts:
      - name: dist

  - name: test
    commands:
      - npm run test:program-rust
    resources:
      - name: dist

  - name: deploy
    commands:
      - echo "deploying..."
    resources:
      - name: target